### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by migpimenta** [cmoro-deusto/docker-tomcat8#2]
Hi Carlos Moro @dordoka 

Thanks very much for your tomcat8 docker image, this has been working very well for me.

I just wanted to point out what can be a potential security issue: some people might be using your image without realising that there's a admin/admin tomcat user. An attacker can login into tomcat console and deploy a malicious WAR file.

I suggest removing this tomcat-users.xml completely, and let image users to extend your image adding their own users/passwords. I can raise a PR for that if you want me to.

Hope this helps.

Best,
Miguel

**Comment by cmoro-deusto** [comment]
Hi @pimentmi 

Thanks a lot for your suggestion. You're right about that. 

Nevertheless, the image has been already downloaded 10K+ times and surely there are also users that know and rely on that `tomcat-users.xml` file being present.

I will update the README to include a warning section describing the existence of said file and the admin user with trivial password.

I guess the right thing to do (tm) would be to accept env vars for the admin username and pass. I might modify the image when I get some free time for that. If you feel like it, I would be happy to merge a rebased PR containing that change.

Regards

C.
