### ISSUE TITLE
tomcat outdated version 8.0.37

### ISSUE THREAD

**Issue by rluncasu** [cmoro-deusto/docker-tomcat8#3]
### The version needs updating. Currently, the available versions at that location are :
[DIR] Parent Directory                             -   
[DIR] v8.0.39/                14-Nov-2016 10:05    -   
[DIR] v8.5.8/                 08-Nov-2016 11:45    -   
[DIR] v8.5.9/                 08-Dec-2016 21:50    -

**Comment by cmoro-deusto** [comment]
Updated to Tomcat 8.0.39 and JDK 8u111 22eb8fe
