### ISSUE TITLE
How do you launch your web app stored in the volume ?

### ISSUE THREAD

**Issue by OUALIDBO** [cmoro-deusto/docker-tomcat8#7]
I taped firefox localhost:8080/opt/tomcat/webapps in the terminal but the page is blank

**Comment by cmoro-deusto** [comment]
I'm not sure if I understand your question correctly. 

I assume you have your web app stored in a directory in your machine. Let's say it's stored in `"/path/to/myapp"` as a war or exploded.

You should run it like this:

```
sudo docker run -d -p 8080:8080 -p 8009:8009 -v /path/to/myapp:/opt/tomcat/webapps dordoka/tomcat
```

Once it's started, you just access it like this:

```
http://localhost:8080
```

The paths after that are the ones that you have exposed in your webapp, no need to prepend "/opt/tomcat/apps".

Hope this helps.

**Comment by OUALIDBO** [comment]
when I attach a volume, the page is always blank

**Comment by cmoro-deusto** [comment]
I would need more information if you want to get any help.
